version: '3'

services:
  scraper:
    networks:
      - scraper
    build:
      ./scraper
    image:
      budgetcat-scraper
    ports:
      - 9999:8080
    expose:
      - 8080
    env_file:
      - ./scraper/.env

  storage:
    env_file:
      - ./storage/.env
    networks:
      - storage
    build:
      ./storage
    image:
      budgetcat-storage
    ports:
      - 9998:8080
    expose:
      - 8080

  db:
    image:
      postgres
    networks:
      - storage
    ports:
      - 5432:5432
    expose:
      - 5432
    env_file:
      - ./storage/.env
    volumes:
      - ./budgetcat_postgres_data_container:/data/budgetcat/db

networks:
  storage:
  scraper:

volumes:
  budgetcat_postgres_data_container:
